Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Exibir um numero antecessor
// Autor(a)    : Ana Cristina
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero")
Leia(numero1)
antecessor<-numero1-1
Escreval("O antecessor é:",antecessor)

Fimalgoritmo