Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Exibir como resposta o numero sucessor
// Autor(a)    : Ana Cristina
// Data atual  : 31/08/2022
Var
// Seção de Declarações das variáveis 
numero1:inteiro
sucessor:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um numero")
Leia(numero1)
sucessor<-numero1+1
Escreval("O sucessor é:",sucessor)

Fimalgoritmo