Algoritmo "Exercicio04-Para"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ana Cristina
// Data atual  : 01/10/2022
Var
// Seção de Declarações das variáveis 
contadora,soma:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 1 ate 500 passo 1 faca
soma<-soma+contadora
Escreval(soma)
fimpara

Fimalgoritmo